server:
  port: 8080

spring:
  profiles:
    default: local
    include: aws

  datasource:
    url: jdbc:h2:tcp://localhost/~/meethere;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      show-sql: true

  output:
    ansi:
      enabled: always
