server:
  port: 8080

spring:
  profiles:
    default: local
    include: aws

  datasource:
    url: jdbc:h2:tcp://localhost/~/meethere;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        format_sql: true
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: grchoi1087@gmail.com
    password: dfrrkhgyqjemjtmq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  output:
    ansi:
      enabled: always
