server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/meethere
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  config:
    activate:
      on-profile: local

logging:
  level:
    org.hibernate.SQL: debug

