server:
  port: 8080

spring:
  profiles:
    default: local
    include: aws

  datasource:
    url: jdbc:h2:tcp://localhost/~/meethere;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        format_sql: true
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: grchoi1087@gmail.com
    password: dfrrkhgyqjemjtmq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # swagger 열기 위해서, spring 2.6.0 이후로 ant_path_parser 로 변경되었기 때문에, 설정 필요
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  output:
    ansi:
      enabled: always
